# Generated by Django 2.2 on 2019-02-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mother_first_name', models.CharField(max_length=100)),
                ('mother_last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(max_length=100)),
                ('child_last_name', models.CharField(max_length=100)),
                ('child_mom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradedApp2.Mother')),
            ],
        ),
    ]
